export const beginnerArea = {
  higurashi: {
    center: {
      goal: { number: 3, rotation: 180 },
      northWest: { number: 4, rotation: 270 },
      north: { number: 2, rotation: 90 },
      northEast: { number: 7, rotation: 0 },
      west: { number: 1, rotation: 180 },
      center: { number: 6, rotation: 270 },
      east: { number: 11, rotation: 180 },
      southWest: { number: 9, rotation: 270 },
      south: { number: 10, rotation: 90 },
      southEast: { number: 5, rotation: 270 },
      start: { number: 8, rotation: 0 },
    },
    edge: {
      northNorthWest: 7,
      northNorthEast: 9,
      eastNorthEast: 1,
      east: 3,
      eastSouthEast: 8,
      southSouthEast: 10,
      south: 0,
      southSouthWest: 4,
      westSouthWest: 2,
      west: 6,
      westNorthWest: 5,
    },
    corner: { northWest: 3, northEast: 1, southEast: 4, southWest: 2 },
  },
  shinen: {
    center: {
      goal: { number: 10, rotation: 0 },
      northWest: { number: 7, rotation: 90 },
      north: { number: 3, rotation: 180 },
      northEast: { number: 5, rotation: 0 },
      west: { number: 9, rotation: 0 },
      center: { number: 8, rotation: 90 },
      east: { number: 6, rotation: 270 },
      southWest: { number: 4, rotation: 0 },
      south: { number: 1, rotation: 90 },
      southEast: { number: 11, rotation: 0 },
      start: { number: 2, rotation: 0 },
    },
    edge: {
      northNorthWest: 7,
      northNorthEast: 9,
      eastNorthEast: 8,
      east: 4,
      eastSouthEast: 2,
      southSouthEast: 10,
      south: 0,
      southSouthWest: 3,
      westSouthWest: 5,
      west: 6,
      westNorthWest: 1,
    },
    corner: { northWest: 4, northEast: 2, southEast: 3, southWest: 1 },
  },
  ensou: {
    center: {
      goal: { number: 3, rotation: 180 },
      northWest: { number: 4, rotation: 90 },
      north: { number: 11, rotation: 90 },
      northEast: { number: 10, rotation: 90 },
      west: { number: 6, rotation: 180 },
      center: { number: 7, rotation: 90 },
      east: { number: 2, rotation: 270 },
      southWest: { number: 8, rotation: 90 },
      south: { number: 9, rotation: 0 },
      southEast: { number: 5, rotation: 90 },
      start: { number: 1, rotation: 0 },
    },
    edge: {
      northNorthWest: 1,
      northNorthEast: 3,
      eastNorthEast: 7,
      east: 10,
      eastSouthEast: 6,
      southSouthEast: 8,
      south: 0,
      southSouthWest: 2,
      westSouthWest: 4,
      west: 5,
      westNorthWest: 9,
    },
    corner: { northWest: 1, northEast: 2, southEast: 3, southWest: 4 },
  },
  gaien: {
    center: {
      goal: { number: 8, rotation: 270 },
      northWest: { number: 7, rotation: 90 },
      north: { number: 4, rotation: 270 },
      northEast: { number: 10, rotation: 180 },
      west: { number: 5, rotation: 0 },
      center: { number: 3, rotation: 270 },
      east: { number: 1, rotation: 0 },
      southWest: { number: 6, rotation: 90 },
      south: { number: 9, rotation: 270 },
      southEast: { number: 2, rotation: 90 },
      start: { number: 0, rotation: 0 },
    },
    edge: {
      northNorthWest: 8,
      northNorthEast: 9,
      eastNorthEast: 5,
      east: 1,
      eastSouthEast: 11,
      southSouthEast: 3,
      south: 10,
      southSouthWest: 4,
      westSouthWest: 7,
      west: 6,
      westNorthWest: 2,
    },
    corner: { northWest: 1, northEast: 2, southEast: 3, southWest: 4 },
  },
};
